<div style="
    background: linear-gradient(140deg, #0f0f0f 0%, #121212 40%, #1DB954 140%);
    padding: 40px 20px 45px 20px;
    border-radius: 18px;
    text-align: center;
    margin-top: 10px;
    margin-bottom: 25px;
    box-shadow: 0 10px 35px rgba(0,0,0,0.6);
    width: 97%;
"

<img src="logo.png" width="90" style="margin-bottom:18px; filter: drop-shadow(0px 6px 10px rgba(29,185,84,0.6));">
<!-- <img src="logo-spotify.jpg" width="90" style="margin-bottom:18px; filter: drop-shadow(0px 6px 10px rgba(29,185,84,0.6));"> -->


<div style="
    font-size: 2.6em;
    font-weight: 800;
    letter-spacing: 1px;
    color: white;
    margin-bottom: 8px;
">
    Tratamento e Limpeza de Dados
</div>

<div style="
    font-size: 3.2em;
    font-weight: 900;
    color: #1DB954;
    text-shadow: 0px 0px 18px rgba(29,185,84,0.45);
">
    Spotify
</div>

<div style="
    margin-top: 14px;
    color: #b3b3b3;
    font-size: 1.05em;
">
    Ciências de Dados - 3ºH - 2026
</div>

</div>

# Bibliotecas

In [33]:

# Importar bibliotecas
import pandas as pd
import json
import glob
import matplotlib.pyplot as plt
import os
from sqlalchemy import create_engine
from dotenv import load_dotenv
from sqlalchemy import text
from sqlalchemy import select, Table, MetaData
from pangres import upsert
# import spotipy
# from spotipy.oauth2 import SpotifyOAuth

# Pegando infos das dimensões

In [34]:
# Carregar variáveis do .env
load_dotenv()

DB_HOST = os.getenv("DB_HOST")
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_PORT = os.getenv("DB_PORT")

# Criar string de conexão
DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# Criar engine
engine = create_engine(DATABASE_URL)
metadata_obj = MetaData()

# StreamingHistory

## Bases

<div style="
    background: linear-gradient(145deg, #121212 0%, #181818 60%, #1DB95422 140%);
    padding: 26px 28px;
    border-radius: 16px;
    margin-top: 20px;
    width: 97%;
    color: #EAEAEA;
    box-shadow: 0 8px 22px rgba(0,0,0,0.55);
">

<div style="
    font-size: 1.9em;
    font-weight: 800;
    color: #1DB954;
margin-bottom: 10px;
">
    Arquivo 1 — Dados de Streaming
</div>

<div style="line-height:1.7;">

<div style="margin-bottom:14px;">
    <span style="color:#1DB954; font-weight:700;">Streaming_History_Audio[...]</span><br>
    Histórico de conteúdos em áudio: músicas, podcasts e audiobooks.
</div>

<div style="margin-bottom:14px;">
    <span style="color:#1DB954; font-weight:700;">Streaming_History_Video[...]</span><br>
    Histórico de conteúdos em vídeo: podcasts com vídeo, clipes e conteúdo visual.
</div>

<div style="
    margin-top:18px;
    padding:14px;
    border-radius:10px;
    background:#1DB95418;
    border-left:5px solid #1DB954;
    font-weight:600;
">
    📊 Nesta análise serão utilizados apenas os dados de <b>áudio</b>.
</div>

</div>

</div>

In [35]:
# Puxando arquivos de áudio 
audio_files = glob.glob("Streaming_History_Audio*.json")

dfs = []

for file in audio_files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        df_temp = pd.DataFrame(data)
        df_temp["source_file"] = file 
        dfs.append(df_temp)


# Mesclando áudios 
df_streaming_history = pd.concat(dfs, ignore_index=True)

# Mostrando o dataframe final de áudio
df_streaming_history.head(5)

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,source_file
0,2021-09-24T12:38:12Z,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",0,BR,179.226.183.56,Baile do Cinga do 12,MC Gontijo,Baile do Cinga do 12,spotify:track:2uLt06E9xCZVPFXg9v794o,NaN,...,None,None,clickrow,unexpected-exit,False,False,False,NaN,False,Streaming_History_Audio_2021-2025_1.json
1,2021-09-24T12:38:12Z,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",0,BR,179.226.183.56,Baile do Cinga do 12,MC Gontijo,Baile do Cinga do 12,spotify:track:2uLt06E9xCZVPFXg9v794o,NaN,...,None,None,clickrow,unexpected-exit,False,False,False,NaN,False,Streaming_History_Audio_2021-2025_1.json
2,2021-09-24T12:45:25Z,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",91975,BR,179.226.183.56,Baile do Cinga do 12,MC Gontijo,Baile do Cinga do 12,spotify:track:2uLt06E9xCZVPFXg9v794o,NaN,...,None,None,clickrow,trackdone,False,False,False,NaN,False,Streaming_History_Audio_2021-2025_1.json
3,2021-09-24T12:45:27Z,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",1770,BR,179.226.183.56,BALANÇA A GLOCK,Mc Jajau,BALANÇA A GLOCK,spotify:track:4PUjVQcrNhH85XXyXnnjBd,NaN,...,None,None,trackdone,backbtn,False,False,False,NaN,False,Streaming_History_Audio_2021-2025_1.json
4,2021-09-24T12:45:30Z,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",2353,BR,179.226.183.56,Menina Se Prepara,Mc Pepeu,Menina Se Prepara,spotify:track:2aqqXrjrPdRHU9uSeRmL3C,NaN,...,None,None,backbtn,endplay,False,False,False,NaN,False,Streaming_History_Audio_2021-2025_1.json

In [36]:
df_streaming_history.info()
df_streaming_history.dropna()

<class 'pandas.DataFrame'>
RangeIndex: 27504 entries, 0 to 27503
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 27504 non-null  str
 1   platform                           27504 non-null  str
 2   ms_played                          27504 non-null  int64
 3   conn_country                       27504 non-null  str
 4   ip_addr                            27503 non-null  str
 5   master_metadata_track_name         27484 non-null  str
 6   master_metadata_album_artist_name  27484 non-null  str
 7   master_metadata_album_album_name   27484 non-null  str
 8   spotify_track_uri                  27484 non-null  str
 9   episode_name                       20 non-null     str
 10  episode_show_name                  20 non-null     str
 11  spotify_episode_uri                20 non-null     str
 12  audiobook_title                    0 non-null      object
 13  audiobook_uri                      0 non-null      object
 14  audiobook_chapter_uri              0 non-null      object
 15  audiobook_chapter_title            0 non-null      object
 16  reason_start                       27504 non-null  str
 17  reason_end                         27504 non-null  str
 18  shuffle                            27504 non-null  bool
 19  skipped                            27504 non-null  bool
 20  offline                            27504 non-null  bool
 21  offline_timestamp                  27322 non-null  float64
 22  incognito_mode                     27504 non-null  bool
 23  source_file                        27504 non-null  str
dtypes: bool(4), float64(1), int64(1), object(4), str(14)
memory usage: 4.3+ MB

Empty DataFrame
Columns: [ts, platform, ms_played, conn_country, ip_addr, master_metadata_track_name, master_metadata_album_artist_name, master_metadata_album_album_name, spotify_track_uri, episode_name, episode_show_name, spotify_episode_uri, audiobook_title, audiobook_uri, audiobook_chapter_uri, audiobook_chapter_title, reason_start, reason_end, shuffle, skipped, offline, offline_timestamp, incognito_mode, source_file]
Index: []

[0 rows x 24 columns]

## Limpeza de dados

In [37]:
# Limpeza de dados 
df_streaming_history = df_streaming_history.drop(columns=["ip_addr", "audiobook_title", "audiobook_uri", "audiobook_chapter_uri", "audiobook_chapter_title", "source_file", "offline_timestamp"])

## Tratamento de colunas

In [38]:
df_streaming_history["ts"] = pd.to_datetime(df_streaming_history["ts"])
df_streaming_history["is_podcast"] = df_streaming_history.apply(
    lambda x: True if pd.notna(x["episode_name"]) else False,
    axis=1
) # Criação de coluna para diferenciar música de podcast


# Renomeando as colunas
column_rename_map = {
    "ts": "played_at",  
    "platform": "platform_used",  
    "ms_played": "milliseconds_played",  
    "conn_country": "connection_country",  

    "master_metadata_track_name": "track_name",  
    "master_metadata_album_artist_name": "artist_name",  
    "master_metadata_album_album_name": "album_name",  
    "spotify_track_uri": "track_uri",  

    "episode_name": "podcast_episode_name",   
    "episode_show_name": "podcast_show_name",  
    "spotify_episode_uri": "podcast_episode_uri",  


    "reason_start": "play_start_reason",  
    "reason_end": "play_end_reason",  

    "shuffle": "shuffle_enabled",  
    "skipped": "skipped_track",  
    "offline": "offline_playback",  
    "offline_timestamp": "offline_timestamp",  

    "incognito_mode": "incognito_mode"
}
df_streaming_history = df_streaming_history.rename(columns=column_rename_map)

## Ajustando o podcast

In [39]:
podcast_df = df_streaming_history.copy()
df_streaming_history.head(1)

,played_at,platform_used,milliseconds_played,connection_country,track_name,artist_name,album_name,track_uri,podcast_episode_name,podcast_show_name,podcast_episode_uri,play_start_reason,play_end_reason,shuffle_enabled,skipped_track,offline_playback,incognito_mode,is_podcast
0,2021-09-24 12:38:12+00:00,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",0,BR,Baile do Cinga do 12,MC Gontijo,Baile do Cinga do 12,spotify:track:2uLt06E9xCZVPFXg9v794o,NaN,NaN,NaN,clickrow,unexpected-exit,False,False,False,False,False

In [40]:
mask = podcast_df["podcast_episode_uri"].notna()

podcast_df.loc[mask, "track_name"] = podcast_df.loc[mask, "podcast_episode_name"]
podcast_df.loc[mask, "album_name"] = podcast_df.loc[mask, "podcast_show_name"]
podcast_df.loc[mask, "artist_name"] = podcast_df.loc[mask, "podcast_show_name"]
podcast_df.loc[mask, "track_uri"] = podcast_df.loc[mask, "podcast_episode_uri"]

podcast_df = podcast_df.drop(columns=["podcast_episode_name","podcast_show_name", "podcast_episode_uri"])
podcast_df.head(1)

,played_at,platform_used,milliseconds_played,connection_country,track_name,artist_name,album_name,track_uri,play_start_reason,play_end_reason,shuffle_enabled,skipped_track,offline_playback,incognito_mode,is_podcast
0,2021-09-24 12:38:12+00:00,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",0,BR,Baile do Cinga do 12,MC Gontijo,Baile do Cinga do 12,spotify:track:2uLt06E9xCZVPFXg9v794o,clickrow,unexpected-exit,False,False,False,False,False

## Normalização dos dados

## Tracks

In [41]:
unique_tracks = podcast_df[["track_name", "track_uri"]].drop_duplicates()
df_tracks = unique_tracks
df_tracks = df_tracks.drop_duplicates(subset='track_name', keep='first')
df_tracks = df_tracks.rename(columns={"track_uri":"uri"})
df_tracks.head(2)

             track_name                                   uri
0  Baile do Cinga do 12  spotify:track:2uLt06E9xCZVPFXg9v794o
3       BALANÇA A GLOCK  spotify:track:4PUjVQcrNhH85XXyXnnjBd

## Album

In [42]:
unique_albuns = podcast_df[["album_name"]].drop_duplicates()
df_albuns = unique_albuns
df_albuns.head(2)

             album_name
0  Baile do Cinga do 12
3       BALANÇA A GLOCK

## Artist

In [43]:
unique_artists = podcast_df[["artist_name"]].drop_duplicates()
df_artists = unique_artists
df_artists.head(2)

  artist_name
0  MC Gontijo
3    Mc Jajau

## Colocando no banco e pegando os dfs de verdade

### Colocando

In [44]:
# Tracks
df_tracks.set_index('track_name', inplace=True)

upsert(con=engine,
       df=df_tracks,
       table_name='Tracks',
       if_row_exists='ignore')

# Artist
df_artists.set_index('artist_name', inplace=True)

upsert(con=engine,
       df=df_artists,
       table_name='Artist',
       if_row_exists='ignore')

# Album
df_albuns.set_index('album_name', inplace=True)

upsert(con=engine,
       df=df_albuns,
       table_name='Album',
       if_row_exists='ignore')

### Pegando

In [45]:
tracks_table = Table("Tracks", metadata_obj, autoload_with=engine)

tracks = {
    "id":[],
    "track_name":[],
    "uri":[]
}

with engine.connect() as conn:
    # Create the select statement
    stmt = select(tracks_table)
    
    # Execute and iterate
    for row in conn.execute(stmt):
        tracks["id"].append(row.id)
        tracks["track_name"].append(row.track_name)
        tracks["uri"].append(row.uri)

df_tracks = pd.DataFrame(tracks)
df_tracks.head(2)

      id           track_name                                   uri
0  74116               Clocks  spotify:track:0BCPKOYdS2jbQ8iyB56Zns
1  74117  Talking to the Moon  spotify:track:1wVuPmvt6AWvTL5W2GJnzZ

In [46]:
artists_table = Table("Artist", metadata_obj, autoload_with=engine)

artists = {
    "id":[],
    "artist_name":[],
    "uri":[]
}

with engine.connect() as conn:
    # Create the select statement
    stmt = select(artists_table)
    
    # Execute and iterate
    for row in conn.execute(stmt):
        artists["id"].append(row.id)
        artists["artist_name"].append(row.artist_name)
        artists["uri"].append(row.uri)

df_artists = pd.DataFrame(artists)
df_artists.head(2)

      id artist_name   uri
0  48487    Coldplay  None
1  48488  Bruno Mars  None

In [47]:
albums_table = Table("Album", metadata_obj, autoload_with=engine)

albums = {
    "id":[],
    "album_name":[],
    "uri":[]
}

with engine.connect() as conn:
    # Create the select statement
    stmt = select(albums_table)
    
    # Execute and iterate
    for row in conn.execute(stmt):
        albums["id"].append(row.id)
        albums["album_name"].append(row.album_name)
        albums["uri"].append(row.uri)

df_albums = pd.DataFrame(albums)
df_albums

         id                                 album_name   uri
0     64389                A Rush of Blood to the Head  None
1     64390                       Doo-Wops & Hooligans  None
2     64391                             Red Pill Blues  None
3     64392                              Night Visions  None
4     64393  Viva La Vida or Death and All His Friends  None
...     ...                                        ...   ...
7101  71490                   Princípios de um Campeão  None
7102  71491                             Brota Na Penha  None
7103  71492                  Ela Vem Sentando por Cima  None
7104  71493                         SET DO JAPA NK 2.0  None
7105  71494                              Name In Blood  None

[7106 rows x 3 columns]

## StreamingHistory

In [48]:
final_streaming_history = podcast_df.copy()

In [49]:
final_streaming_history = final_streaming_history.merge(df_artists[['artist_name', 'id']], on='artist_name', how='left')
final_streaming_history = final_streaming_history.rename(columns={'id': 'artist_id'})

final_streaming_history = final_streaming_history.merge(df_tracks[['track_name', 'id']], on='track_name', how='left')
final_streaming_history = final_streaming_history.rename(columns={'id': 'track_id'})

final_streaming_history = final_streaming_history.merge(df_albums[['album_name', 'id']], on='album_name', how='left')
final_streaming_history = final_streaming_history.rename(columns={'id': 'album_id'})
final_streaming_history.head(1)

,played_at,platform_used,milliseconds_played,connection_country,track_name,artist_name,album_name,track_uri,play_start_reason,play_end_reason,shuffle_enabled,skipped_track,offline_playback,incognito_mode,is_podcast,artist_id,track_id,album_id
0,2021-09-24 12:38:12+00:00,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",0,BR,Baile do Cinga do 12,MC Gontijo,Baile do Cinga do 12,spotify:track:2uLt06E9xCZVPFXg9v794o,clickrow,unexpected-exit,False,False,False,False,False,50613,78199,67891

In [50]:
final_streaming_history = final_streaming_history.drop(columns=["track_name", "track_uri", "artist_name", "album_name"])
final_streaming_history.head(1)

,played_at,platform_used,milliseconds_played,connection_country,play_start_reason,play_end_reason,shuffle_enabled,skipped_track,offline_playback,incognito_mode,is_podcast,artist_id,track_id,album_id
0,2021-09-24 12:38:12+00:00,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",0,BR,clickrow,unexpected-exit,False,False,False,False,False,50613,78199,67891

# LibraryTracks

In [51]:
with open("YourLibrary.json", "r", encoding="utf-8") as f:
    library = json.load(f)

df_library_tracks = pd.json_normalize(library, record_path=['tracks'], sep='_')
df_library_tracks["liked"] = True
df_library_tracks.head()

,artist,album,track,uri,liked
0,Veigh,Nois é Nois,Nois é Nois,spotify:track:1k1egPmIPWQ0J44PWgMDwA,True
1,Mc IG,Todo Mundo Odeia o IG,"Olá, Moça",spotify:track:7umgf0NrHZgIAI0ep64sLc,True
2,LH CHUCRO,2 L3Trinha,Mesma V*,spotify:track:0jboKOUbn8dyW7ihbMiZI2,True
3,Black Sabbath,We Sold Our Soul for Rock 'N' Roll,War Pigs,spotify:track:6BUhl6rrIIqUJgJP4QjJP7,True
4,WIU,Felina,Felina,spotify:track:2orGm2E68ODFYOURjaES62,True

In [52]:
with open('Playlist1.json', 'r', encoding='utf-8') as f:
    playlist_json = json.load(f)

playlists = []
for i in playlist_json["playlists"]:
    playlist = pd.json_normalize(i["items"],sep='_')
    playlist["playlists_lastModifiedDate"] = i["lastModifiedDate"]
    playlist["playlists_name"] = i["name"]
    playlists.append(playlist)

df_playlist = pd.concat(playlists)
df_playlist = df_playlist.rename(columns={"track_trackName": "track", "track_artistName": 'artist', "track_albumName":"album", "track_trackUri":"uri"})
df_playlist = df_playlist[["track", "artist", "album", "uri"]]
df_playlist["in_playlist"] = True
df_playlist.head()

,track,track,artist,album,uri,in_playlist
0,O Vovô Não Ta Casado,NaN,Biurifol,O Vovô Não Ta Casado,spotify:track:1UWDkzoTCX0prwWRuSOgAw,True
1,BEBIDA DROGA E SEXO,NaN,Mc Neguinho do Morro,BEBIDA DROGA E SEXO,spotify:track:7FEn48e1p6CW7th59pyM2h,True
2,Ela ké Leitada,NaN,Prod.Nifour,Ela ké Leitada,spotify:track:161dJFOgyuYcgKg0AzYuAh,True
3,Não Bebo Não Fumo Mais,NaN,MC Ryan SP,Não Bebo Não Fumo Mais,spotify:track:361DsT1rBpJKIYVJNSP0pk,True
4,Princípios de um Campeão,NaN,Chefin,Princípios de um Campeão,spotify:track:63LER5IqaKWNUHeFKFBwBh,True

In [53]:
def nan_to_false(column):
    new_column = []
    for i in column:
        if str(i) == "nan":
            i = False
        new_column.append(i)
    return new_column

In [54]:
df_library_tracks = df_library_tracks.loc[:, ~df_library_tracks.columns.duplicated()]
df_playlist = df_playlist.loc[:, ~df_playlist.columns.duplicated()]

library_df = pd.concat([df_library_tracks, df_playlist],ignore_index=True)
library_df["liked"] = nan_to_false(library_df["liked"])
library_df["in_playlist"] = nan_to_false(library_df["in_playlist"])
library_df.head(1)

,artist,album,track,uri,liked,in_playlist
0,Veigh,Nois é Nois,Nois é Nois,spotify:track:1k1egPmIPWQ0J44PWgMDwA,True,False

In [55]:
final_library_df = library_df.copy()

In [56]:
final_library_df = pd.merge(final_library_df, df_artists[['artist_name', 'id']], left_on="artist", right_on='artist_name', how='left')
final_library_df = final_library_df.rename(columns={'id': 'artist_id'})

final_library_df = pd.merge(final_library_df, df_tracks[['track_name', 'id']], left_on="track", right_on='track_name', how='left')
final_library_df = final_library_df.rename(columns={'id': 'track_id'})

final_library_df = pd.merge(final_library_df, df_albums[['album_name', 'id']], left_on="album", right_on='album_name', how='left')
final_library_df = final_library_df.rename(columns={'id': 'album_id'})
final_library_df = final_library_df[["track_id", "artist_id", "album_id", "in_playlist", "liked"]]
final_library_df.head(1)

   track_id  artist_id  album_id  in_playlist  liked
0   77345.0    48960.0   67150.0        False   True

# Enviar dados para o banco

In [57]:
user_id = 3

print("User ID encontrado:", user_id)

User ID encontrado: 3

In [58]:
# Adicionar a coluna no df 
final_streaming_history["user_id"] = user_id
final_streaming_history = final_streaming_history.drop_duplicates(subset=['played_at'], keep='first')
final_streaming_history.head(2)

,played_at,platform_used,milliseconds_played,connection_country,play_start_reason,play_end_reason,shuffle_enabled,skipped_track,offline_playback,incognito_mode,is_podcast,artist_id,track_id,album_id,user_id
0,2021-09-24 12:38:12+00:00,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",0,BR,clickrow,unexpected-exit,False,False,False,False,False,50613,78199,67891,3
16,2021-09-24 12:45:25+00:00,"Android OS 10 API 29 (Xiaomi, Redmi Note 9S)",91975,BR,clickrow,trackdone,False,False,False,False,False,50613,78199,67891,3

In [59]:
final_library_df["user_id"] = user_id
final_library_df = final_library_df.dropna(subset=["track_id"])
final_library_df = final_library_df.drop_duplicates(subset=["track_id", "user_id"], keep="first")
final_library_df.head(2)

   track_id  artist_id  album_id  in_playlist  liked  user_id
0   77345.0    48960.0   67150.0        False   True        3
2   80828.0    48960.0   67150.0        False   True        3

In [60]:
# Rode caso de tudo errado e tenha q dar rollback
# from sqlalchemy import text

# # This clears the "stuck" transaction
# with engine.connect() as conn:
#     conn.execute(text("ROLLBACK"))

In [61]:
final_streaming_history.set_index(['played_at', 'user_id'], inplace=True)

upsert(con=engine,
       df=final_streaming_history,
       table_name='StreamingHistory',
       if_row_exists='ignore')

In [62]:
final_library_df.set_index(['track_id', 'user_id'], inplace=True)

upsert(con=engine,
       df=final_library_df,
       table_name='LibraryTracks',
       if_row_exists='ignore')

<div style="
    background: linear-gradient(145deg, #121212 0%, #181818 60%, #1DB95422 140%);
    padding: 26px 28px;
    border-radius: 16px;
    margin-top: 20px;
    width: 97%;
    color: #EAEAEA;
    box-shadow: 0 8px 22px rgba(0,0,0,0.55);
">

<div style="
    font-size: 1.9em;
    font-weight: 800;
    color: #1DB954;
    margin-bottom: 16px;
">
    Arquivo 2 — Dados da Conta
</div>

<!-- Wrapped -->
---
<div style="margin-bottom:28px;">
    <div style="font-size:1.35em; font-weight:700; color:#FFFFFF;">
        Wrapped2025.json — Métricas Anuais Agregadas
</div>

<div style="margin-top:10px; line-height:1.7;">
    Estatísticas consolidadas do Spotify Wrapped 2025 representando o comportamento musical ao longo do ano.
</div>

</div>

--- 

<!-- Library -->
<div style="margin-bottom:28px;">
<div style="font-size:1.35em; font-weight:700; color:#FFFFFF;">
    YourLibrary.json — Biblioteca Pessoal
</div>

<div style="margin-top:10px; line-height:1.7;">
    Representa o conteúdo salvo pelo usuário: músicas, álbuns e podcasts.
    Diferente do histórico, reflete preferência declarada e não necessariamente consumo real.
</div>

</div>

--- 

<!-- Capsule -->
<div>
<div style="font-size:1.35em; font-weight:700; color:#FFFFFF;">
    YourSoundCapsule.json — Resumo Diário
</div>

<div style="margin-top:10px; line-height:1.7;">
    Estatísticas diárias de consumo musical: quantidade de streams,
    tempo ouvido e ranking diário de músicas e artistas.
</div>



</div>

### Wrapped

In [63]:
# Carregando Wrapped2025.json
with open("Wrapped2025.json", "r", encoding="utf-8") as f:
    wrapped = json.load(f)

wrapped.keys()

# fazer um df com wrapped 
df_wrapped = pd.DataFrame(wrapped)
df_wrapped.info()

<class 'pandas.DataFrame'>
Index: 40 entries, topArtistUris to insights
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   topArtists     4 non-null      object
 1   topTracks      2 non-null      object
 2   yearlyMetrics  1 non-null      float64
 3   topAlbums      3 non-null      object
 4   topGenres      2 non-null      object
 5   clubs          4 non-null      object
 6   listeningAge   3 non-null      object
 7   party          19 non-null     object
 8   topArtistRace  3 non-null      object
dtypes: float64(1), object(8)
memory usage: 3.1+ KB

In [64]:
# Tratar dados do wrapped